const parrafos = {
	RiverBank: {
		title: 'River Bank',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.30 x 0.90 mts',
	},
	Mousteire: {
		title: 'Mousteire',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.30 x 0.90 mts',
	},
	Curl: {
		title: 'Curl',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.20 x 0.90 mts',
	},
	Gold: {
		title: 'Gold',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.20 x 0.90 mts',
	},
	Fun: {
		title: 'Fun',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '0.70 x 1.80 mts',
	},
	Stripping: {
		title: 'Stripping',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.00 x 1.00 mts',
	},
	Naif: {
		title: 'Naif',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.20 x 1.20 mts',
	},
	Youth: {
		title: 'Naif',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.00 x 1.00 mts',
	},
	NYC: {
		title: 'NYC',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.00 x 1.00 mts',
	},
	Pantuss: {
		title: 'Pantuss',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.00 x 1.00 mts',
	},
	Drums: {
		title: 'Drums',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.00 x 1.00 mts',
	},
	Chaos: {
		title: 'Chaos',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.20 x 1.20 mts',
	},
	Dauntless: {
		title: 'Dauntless',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.40 x 1.40 mts',
	},
	MakeupCase: {
		title: 'Makeup Case',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.40 x 1.20 mts',
	},
	Orchid: {
		title: 'Orchid',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.20 x 1.00 mts',
	},
	LetsFly: {
		title: 'Dauntless',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.10 x 1.30 mts',
	},
	ExplosionSeriesI: {
		title: 'Explosion Series I',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.50 x 0.60 mts',
	},
	ExplosionSeriesII: {
		title: 'Explosion Series II',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.50 x 0.60 mts',
	},
	Twilight: {
		title: 'Twilight',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.70 x 0.70 mts',
	},
	Sunset: {
		title: 'Sunset',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.50 x 0.70 mts',
	},
	BeachSeriesI: {
		title: 'Beach Series I',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.70 x 0.60 mts',
	},
	BeachSeriesII: {
		title: 'Beach Series I',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.70 x 0.70 mts',
	},
	BlackLaneSeriesI: {
		title: 'Black Lane Series I',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.60 x 0.60 mts',
	},
	BlackLaneSeriesII: {
		title: 'Black Lane Series II',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.60 x 0.60 mts',
	},
	TenerifeSea: {
		title: 'Tenerife Sea',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.50 x 0.40 mts',
	},
	Sandstrom: {
		title: 'Sandstrom',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.50 x 0.40 mts',
	},
	AshSkySeriesI: {
		title: 'Ash Sky Series I',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.40 x 0.30 mts',
	},
	AshSkySeriesII: {
		title: 'Ash Sky Series II',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.40 x 0.30 mts',
	},
	Laugh: {
		title: 'Laugh',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.90 x 1.10 mts',
	},
	Begining: {
		title: 'Laugh',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.10 x 1.10 mts',
	},
	CloudySunset: {
		title: 'Cloudy Sunset',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.10 x 1.10 mts',
	},
	Gale: {
		title: 'Gale',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.50 x 0.50 mts',
	},
	Calm: {
		title: 'Calm',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.80 x 0.60 mts',
	},
	Underworld: {
		title: 'Underworld',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '0.90 x 0.60 mts',
	},
	Vision: {
		title: 'Vision',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.20 x 1.60 mts',
	},
	Parrots: {
		title: 'Parrots',
		location: 'Buenos Aires,2021',
		style: 'Acrylic on canvas',
		content: '1.80 x 0.70 mts',
	},
	Palette: {
		title: 'Palette',
		location: 'Buenos Aires,2020',
		style: 'Acrylic on canvas',
		content: '1.20 x 1.20 mts',
	},
	Cement: {
		title: 'Palette',
		location: 'Buenos Aires,2020',
		style: 'Acrylic on canvas',
		content: '1.00 x 0.80 mts',
	},
	CyanSeriesI: {
		title: 'Cyan Series I',
		location: 'Buenos Aires,2020',
		style: 'Acrylic on canvas',
		content: '0.30 x 0.80 mts',
	},
	CyanSeriesII: {
		title: 'Cyan Series II',
		location: 'Buenos Aires,2020',
		style: 'Acrylic on canvas',
		content: '0.30 x 0.80 mts',
	},
	Colors: {
		title: 'Colors',
		location: 'Buenos Aires,2020',
		style: 'Acrylic on canvas',
		content: '1.60 x 0.80 mts',
	},
	Frida: {
		title: 'Frida',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas',
		content: '1.20 x 1.20 mts',
	},
	Aqua: {
		title: 'Aqua',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas',
		content: '1.30 x 1.10 mts',
	},
	Shining: {
		title: 'Shining',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas',
		content: '1.10 x 1.10 mts',
	},
	Birds: {
		title: 'Birds',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas',
		content: '0.90 x 1.30 mts',
	},
	Souls: {
		title: 'Souls',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas , mixed technique',
		content: '1.60 x 0.70 mts',
	},
	Rhythm: {
		title: 'Rhythm',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas ',
		content: '0.80 x 0.80 mts',
	},
	Moss: {
		title: 'Moss',
		location: 'Buenos Aires,2019',
		style: 'Acrylic on canvas ',
		content: '0.80 x 0.80 mts',
	},
	Mosaic: {
		title: 'Mosaic',
		location: 'Buenos Aires,2018',
		style: 'Acrylic on canvas ',
		content: '1.20 x 1.20 mts',
	},
	Hole: {
		title: 'Hole',
		location: 'Buenos Aires,2018',
		style: 'Acrylic on canvas, mixed technique',
		content: '1.20 x 1.20 mts',
		state: 'Sold',
	},
	Beat: {
		title: 'Beat',
		location: 'Buenos Aires,2018',
		style: 'Acrylic on canvas',
		content: '0.90 x 0.60 mts',
	},
	Violet: {
		title: 'Violet',
		location: 'Buenos Aires,2022',
		style: 'Acrylic on canvas',
		content: '1.30 x 0.90 mts',
	},

	// ... agrega el resto de los párrafos
};

export default parrafos;
